# -*- coding: utf-8 -*-
"""脚本模板数据模块 - 从 main_window.py 提取
包含 PowerShell / Batch / Shell 三种脚本类型的 GROMACS 流程模板。
"""


def get_script_template(script_type, key, gmx_norm):
    """根据脚本类型和模板键返回脚本文本。

    Args:
        script_type: 脚本类型 (PowerShell / Batch / Shell)
        key: 模板键 (em, full_md, rmsd 等)
        gmx_norm: 正斜杠格式的 GROMACS 可执行文件路径

    Returns:
        str: 脚本模板文本
    """
    gmx_batch = gmx_norm.replace("/", "\\")

    if "PowerShell" in script_type:
        if key == "em":
            text = (
                "# 能量最小化脚本模板 (PowerShell)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 1. 生成拓扑 (如果已有topol.top可跳过)\n"
                "# & $GMX pdb2gmx -f protein.pdb -o protein.gro -p topol.top -ff amber99sb-ildn -water tip3p -ignh\n\n"
                "# 2. 构建盒子\n"
                "& $GMX editconf -f protein.gro -o protein_box.gro -c -d 1.0 -bt cubic\n\n"
                "# 3. 溶剂化\n"
                "& $GMX solvate -cp protein_box.gro -o protein_solv.gro -p topol.top\n\n"
                "# 4. 能量最小化\n"
                "& $GMX grompp -f em.mdp -c protein_solv.gro -p topol.top -o em.tpr -maxwarn 2\n"
                "& $GMX mdrun -deffnm em -v\n\n"
                "Write-Host \"能量最小化完成!\"\n"
            )
        elif key == "full_md":
            text = (
                "# 完整MD流程脚本模板 (EM -> NVT -> NPT -> MD)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "$steps = @(\n"
                "    @{name='EM';  mdp='em.mdp';  prev='protein_solv.gro'; out='em'},\n"
                "    @{name='NVT'; mdp='nvt.mdp'; prev='em.gro';       out='nvt'},\n"
                "    @{name='NPT'; mdp='npt.mdp'; prev='nvt.gro';      out='npt'},\n"
                "    @{name='MD';  mdp='md.mdp';  prev='npt.gro';      out='md'}\n"
                ")\n\n"
                "foreach ($s in $steps) {\n"
                "    Write-Host \"==== 运行 $($s.name) ====\" -ForegroundColor Cyan\n"
                "    & $GMX grompp -f $s.mdp -c $s.prev -r $s.prev -p topol.top -o \"$($s.out).tpr\" -maxwarn 2\n"
                "    if ($LASTEXITCODE -ne 0) { Write-Error \"grompp 失败\"; exit 1 }\n"
                "    & $GMX mdrun -deffnm $s.out -v\n"
                "    if ($LASTEXITCODE -ne 0) { Write-Error \"mdrun 失败\"; exit 1 }\n"
                "    Write-Host \"$($s.name) 完成\" -ForegroundColor Green\n"
                "}\n\n"
                "Write-Host \"所有MD步骤完成!\" -ForegroundColor Green\n"
            )
        elif key == "clffcl_em_npt":
            text = (
                "# ClFFCl EM+NPT流程模板 (PowerShell)\n"
                "# 流程: EM-1 → EM-2 → NPT-1 → NPT-2\n"
                "# 使用文件: ydw-em_01.mdp (steep), ydw-em_02.mdp (cg), ydw-npt_01.mdp (1ns), ydw-npt_02.mdp (2ns)\n"
                "# 输入: ydw-PM6-ClFFCl.pdb, p4PM6-ClFFCl-mix.top\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# ==== Step 1: 能量最小化 EM-1 (steep) ====\n"
                "Write-Host \"==== 运行 EM-1 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f ydw-em_01.mdp -c ydw-PM6-ClFFCl.pdb -p p4PM6-ClFFCl-mix.top -o ClFFCl_em1.tpr -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"EM-1 grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm ClFFCl_em1 -nt 6 -pin on -nb gpu -pme cpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"EM-1 mdrun 失败\"; exit 1 }\n"
                "Write-Host \"EM-1 完成\" -ForegroundColor Green\n\n"
                "# ==== Step 2: 能量最小化 EM-2 (cg) ====\n"
                "Write-Host \"==== 运行 EM-2 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f ydw-em_02.mdp -c ClFFCl_em1.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_em2.tpr -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"EM-2 grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm ClFFCl_em2 -nt 6 -pin on -nb gpu -pme cpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"EM-2 mdrun 失败\"; exit 1 }\n"
                "Write-Host \"EM-2 完成\" -ForegroundColor Green\n\n"
                "# ==== Step 3: NPT 平衡 1 (1ns) ====\n"
                "Write-Host \"==== 运行 NPT-1 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f ydw-npt_01.mdp -c ClFFCl_em2.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_npt1.tpr -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"NPT-1 grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm ClFFCl_npt1 -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"NPT-1 mdrun 失败\"; exit 1 }\n"
                "Write-Host \"NPT-1 完成\" -ForegroundColor Green\n\n"
                "# ==== Step 4: NPT 平衡 2 (2ns) ====\n"
                "Write-Host \"==== 运行 NPT-2 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f ydw-npt_02.mdp -c ClFFCl_npt1.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_npt2.tpr -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"NPT-2 grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm ClFFCl_npt2 -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"NPT-2 mdrun 失败\"; exit 1 }\n"
                "Write-Host \"NPT-2 完成\" -ForegroundColor Green\n\n"
                "Write-Host \"所有步骤完成!\" -ForegroundColor Green\n"
            )
        elif key == "clffcl_sa":
            text = (
                "# ClFFCl SA溶剂蒸发流程模板 (PowerShell)\n"
                "# 流程: 逐步删除CF溶剂分子，每轮运行10ps NPT\n"
                "# 使用文件: ydw-npt-sa.mdp\n"
                "# 输入: ClFFCl_npt2.gro, p4PM6-ClFFCl-mix.top\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 配置参数\n"
                "$inputGro = \"ClFFCl_npt2.gro\"\n"
                "$topFile = \"p4PM6-ClFFCl-mix.top\"\n"
                "$mdpFile = \"ydw-npt-sa.mdp\"\n"
                "$prefix = \"ClFFCl_sa\"\n"
                "$loops = 500\n"
                "$deleteNum = 100\n"
                "$atomsPerSolvent = 5\n\n"
                "# 检查输入文件\n"
                "if (-not (Test-Path $inputGro)) { Write-Error \"输入文件不存在: $inputGro\"; exit 1 }\n"
                "if (-not (Test-Path $topFile)) { Write-Error \"拓扑文件不存在: $topFile\"; exit 1 }\n"
                "if (-not (Test-Path $mdpFile)) { Write-Error \"MDP文件不存在: $mdpFile\"; exit 1 }\n\n"
                "# 备份原始文件\n"
                "Copy-Item $inputGro \"${prefix}_original.gro\" -Force\n"
                "Copy-Item $topFile \"${prefix}_original.top\" -Force\n"
                "Write-Host \"已备份原始文件\" -ForegroundColor Green\n\n"
                "$workGro = \"${prefix}_work.gro\"\n"
                "$workTop = \"${prefix}_work.top\"\n"
                "$currentGro = \"${prefix}_current.gro\"\n"
                "$currentTop = \"${prefix}_current.top\"\n"
                "Copy-Item $inputGro $workGro -Force\n"
                "Copy-Item $topFile $workTop -Force\n\n"
                "for ($i = 1; $i -le $loops; $i++) {\n"
                "    Write-Host \"==== SA 第 $i/$loops 轮 ====\" -ForegroundColor Cyan\n"
                "\n"
                "    $newGro = \"${prefix}_new.gro\"\n"
                "    $newTop = \"${prefix}_new.top\"\n"
                "\n"
                "    Write-Host \"删除 $deleteNum 个CF溶剂分子...\" -ForegroundColor Yellow\n"
                "    python delete_solvent.py --solvent CF --delete-num $deleteNum --atoms-per-mol $atomsPerSolvent --loop $i --input $workGro --output $newGro --topology $workTop --topology-output $newTop\n"
                "    if ($LASTEXITCODE -ne 0) { Write-Error \"删除溶剂失败\"; exit 1 }\n"
                "\n"
                "    Move-Item $newGro $workGro -Force\n"
                "    Move-Item $newTop $workTop -Force\n"
                "\n"
                "    Write-Host \"grompp...\" -ForegroundColor Yellow\n"
                "    & $GMX grompp -f $mdpFile -c $workGro -p $workTop -o \"${prefix}_$i.tpr\" -maxwarn 200\n"
                "    if ($LASTEXITCODE -ne 0) { Write-Error \"grompp 失败\"; exit 1 }\n"
                "\n"
                "    Write-Host \"mdrun (10ps)...\" -ForegroundColor Yellow\n"
                "    & $GMX mdrun -v -deffnm \"${prefix}_$i\" -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "    if ($LASTEXITCODE -ne 0) { Write-Error \"mdrun 失败\"; exit 1 }\n"
                "\n"
                "    Copy-Item \"${prefix}_$i.gro\" $currentGro -Force\n"
                "    Copy-Item $workTop $currentTop -Force\n"
                "    Write-Host \"第 $i 轮完成\" -ForegroundColor Green\n"
                "}\n\n"
                "Write-Host \"SA溶剂蒸发完成!\" -ForegroundColor Green\n"
                "Write-Host \"最终结构: $currentGro\" -ForegroundColor Yellow\n"
                "Write-Host \"最终拓扑: $currentTop\" -ForegroundColor Yellow\n"
            )
        elif key == "clffcl_evapdio":
            text = (
                "# ClFFCl evapDIO流程模板 (PowerShell)\n"
                "# 流程: 删除DIO添加剂 → 运行1ns NPT平衡 → 退火 → MD2\n"
                "# 使用文件: ydw-evapDIO.mdp, ydw-ta.mdp, ydw-md_02.mdp\n"
                "# 输入: ClFFCl_md.gro, ClFFCl_sa_current.top\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 配置参数\n"
                "$inputGro = \"ClFFCl_md.gro\"\n"
                "$inputTop = \"ClFFCl_sa_current.top\"\n"
                "$mdpFile = \"ydw-evapDIO.mdp\"\n"
                "$prefix = \"ClFFCl_evapDIO\"\n\n"
                "# 检查输入文件\n"
                "if (-not (Test-Path $inputGro)) { Write-Error \"输入文件不存在: $inputGro\"; exit 1 }\n"
                "if (-not (Test-Path $inputTop)) { Write-Error \"拓扑文件不存在: $inputTop\"; exit 1 }\n"
                "if (-not (Test-Path $mdpFile)) { Write-Error \"MDP文件不存在: $mdpFile\"; exit 1 }\n\n"
                "# ==== Step 1: 删除DIO添加剂 ====\n"
                "Write-Host \"==== 删除DIO添加剂 ====\" -ForegroundColor Cyan\n"
                "$outGro = \"${prefix}_DA.gro\"\n"
                "$outTop = \"${prefix}.top\"\n"
                "python delete_additive_all.py --additive DIO --atoms-per-mol 6 --input $inputGro --output $outGro --topology $inputTop --topology-output $outTop\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"删除DIO失败\"; exit 1 }\n"
                "Write-Host \"DIO删除完成\" -ForegroundColor Green\n\n"
                "# ==== Step 2: 1ns NPT平衡 ====\n"
                "Write-Host \"==== 运行1ns NPT平衡 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f $mdpFile -c \"${prefix}_DA.gro\" -p \"${prefix}.top\" -o \"${prefix}.tpr\" -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm $prefix -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"mdrun 失败\"; exit 1 }\n"
                "Write-Host \"evapDIO NPT完成\" -ForegroundColor Green\n\n"
                "# ==== Step 3: 退火过程 ====\n"
                "Write-Host \"==== 运行退火 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f ydw-ta.mdp -c \"${prefix}.gro\" -p \"${prefix}.top\" -o \"${prefix}_anneal.tpr\" -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"退火 grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm \"${prefix}_anneal\" -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"退火 mdrun 失败\"; exit 1 }\n"
                "Write-Host \"退火完成\" -ForegroundColor Green\n\n"
                "# ==== Step 4: MD2 生产模拟 ====\n"
                "Write-Host \"==== 运行MD2 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f ydw-md_02.mdp -c \"${prefix}_anneal.gro\" -p \"${prefix}.top\" -o \"${prefix}_md2.tpr\" -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"MD2 grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm \"${prefix}_md2\" -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"MD2 mdrun 失败\"; exit 1 }\n"
                "Write-Host \"MD2完成\" -ForegroundColor Green\n\n"
                "Write-Host \"evapDIO+退火+MD2流程全部完成!\" -ForegroundColor Green\n"
            )
        elif key == "rmsd":
            text = (
                "# RMSD分析脚本模板\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 先做轨迹拟合 (去除平动转动)\n"
                "echo '4' | & $GMX trjconv -s md.tpr -f md.xtc -o md_fit.xtc -fit rot+trans\n\n"
                "# 计算RMSD (骨架原子)\n"
                "echo '4 4' | & $GMX rms -s md.tpr -f md_fit.xtc -o rmsd.xvg -tu ns\n\n"
                "# 计算RMSF\n"
                "echo '3' | & $GMX rmsf -s md.tpr -f md_fit.xtc -o rmsf.xvg -res\n\n"
                "Write-Host \"RMSD/RMSF分析完成!\"\n"
            )
        elif key == "clffcl_md1":
            text = (
                "# ClFFCl MD-1生产模拟流程模板 (PowerShell)\n"
                "# 流程: 基于ClFFCl_npt2.gro运行10ns生产模拟\n"
                "# 使用文件: ydw-md_01.mdp (10ns)\n"
                "# 输入: ClFFCl_npt2.gro, p4PM6-ClFFCl-mix.top\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# ==== Step 1: MD-1 生产模拟 (10ns) ====\n"
                "Write-Host \"==== 运行 MD-1 (10ns) ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f ydw-md_01.mdp -c ClFFCl_npt2.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_md.tpr -maxwarn 200\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"MD-1 grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -v -deffnm ClFFCl_md -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"MD-1 mdrun 失败\"; exit 1 }\n"
                "Write-Host \"MD-1 (10ns)完成\" -ForegroundColor Green\n\n"
                "Write-Host \"ClFFCl MD-1生产模拟完成!\" -ForegroundColor Green\n"
            )
        elif key == "nvt":
            text = (
                "# NVT恒温平衡脚本模板 (PowerShell)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# NVT 恒温平衡\n"
                "Write-Host \"==== 运行 NVT 恒温平衡 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 2\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -deffnm nvt -v\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"mdrun 失败\"; exit 1 }\n"
                "Write-Host \"NVT恒温平衡完成!\" -ForegroundColor Green\n"
            )
        elif key == "npt":
            text = (
                "# NPT恒压平衡脚本模板 (PowerShell)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# NPT 恒压平衡\n"
                "Write-Host \"==== 运行 NPT 恒压平衡 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f npt.mdp -c nvt.gro -r nvt.gro -p topol.top -o npt.tpr -maxwarn 2\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -deffnm npt -v\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"mdrun 失败\"; exit 1 }\n"
                "Write-Host \"NPT恒压平衡完成!\" -ForegroundColor Green\n"
            )
        elif key == "md":
            text = (
                "# MD生产模拟脚本模板 (PowerShell)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# MD 生产模拟\n"
                "Write-Host \"==== 运行 MD 生产模拟 ====\" -ForegroundColor Cyan\n"
                "& $GMX grompp -f md.mdp -c npt.gro -r npt.gro -p topol.top -o md.tpr -maxwarn 2\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"grompp 失败\"; exit 1 }\n"
                "& $GMX mdrun -deffnm md -v\n"
                "if ($LASTEXITCODE -ne 0) { Write-Error \"mdrun 失败\"; exit 1 }\n"
                "Write-Host \"MD生产模拟完成!\" -ForegroundColor Green\n"
            )
        elif key == "rdf":
            text = (
                "# RDF径向分布函数分析脚本模板 (PowerShell)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 计算径向分布函数 (蛋白-溶剂)\n"
                "echo '1 11' | & $GMX rdf -s md.tpr -f md.xtc -o rdf.xvg -ref 'Protein' -sel 'Water'\n\n"
                "# 计算配位数\n"
                "echo '1 11' | & $GMX rdf -s md.tpr -f md.xtc -o rdf_coord.xvg -ref 'Protein' -sel 'Water' -cn\n\n"
                "Write-Host \"RDF分析完成!\"\n"
            )
        elif key == "hbond":
            text = (
                "# 氢键分析脚本模板 (PowerShell)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 计算氢键 (蛋白-蛋白)\n"
                "echo '1 1' | & $GMX hbond -s md.tpr -f md.xtc -num hbond.xvg\n\n"
                "# 计算氢键 (蛋白-溶剂)\n"
                "echo '1 11' | & $GMX hbond -s md.tpr -f md.xtc -num hbond_solv.xvg\n\n"
                "# 氢键寿命分析\n"
                "echo '1 1' | & $GMX hbond -s md.tpr -f md.xtc -ac hbond_analysis.xvg\n\n"
                "Write-Host \"氢键分析完成!\"\n"
            )
        elif key == "sasa":
            text = (
                "# SASA溶剂可及面积分析脚本模板 (PowerShell)\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 计算整体SASA\n"
                "echo '1' | & $GMX sasa -s md.tpr -f md.xtc -o sasa.xvg -surface 1 -output 1\n\n"
                "# 按残基计算SASA\n"
                "echo '3' | & $GMX sasa -s md.tpr -f md.xtc -o sasa_res.xvg -surface 1 -output 2\n\n"
                "# 计算极性/非极性SASA\n"
                "echo '1' | & $GMX sasa -s md.tpr -f md.xtc -o sasa_pol.xvg -surface 2 -output 1\n\n"
                "Write-Host \"SASA分析完成!\"\n"
            )
        elif key == "pca":
            text = (
                "# PCA主成分分析脚本模板 (PowerShell)\n"
                "# 注意：需要先做轨迹拟合\n"
                "$GMX = \"" + gmx_norm + "\"\n"
                "Set-Location $PSScriptRoot\n\n"
                "# 步骤1: 轨迹拟合 (去除平动转动)\n"
                "Write-Host \"==== 轨迹拟合 ====\" -ForegroundColor Cyan\n"
                "echo '4' | & $GMX trjconv -s md.tpr -f md.xtc -o md_fit.xtc -fit rot+trans\n\n"
                "# 步骤2: 计算协方差矩阵\n"
                "Write-Host \"==== 计算协方差矩阵 ====\" -ForegroundColor Cyan\n"
                "echo '4' | & $GMX covar -s md.tpr -f md_fit.xtc -o eigenvectors.trr -xpm covar.xpm\n\n"
                "# 步骤3: 对角化协方差矩阵\n"
                "Write-Host \"==== 对角化协方差矩阵 ====\" -ForegroundColor Cyan\n"
                "& $GMX anaeig -s md.tpr -f eigenvectors.trr -o eigenvalues.xvg -v eigenvectors.trr -n 10\n\n"
                "# 步骤4: 投影到主成分\n"
                "Write-Host \"==== 投影到主成分 ====\" -ForegroundColor Cyan\n"
                "echo '4' | & $GMX anaeig -s md.tpr -f md_fit.xtc -proj pcaprojection.xvg\n\n"
                "# 步骤5: 生成PC1和PC2的结构\n"
                "Write-Host \"==== 生成主成分结构 ====\" -ForegroundColor Cyan\n"
                "echo '4' | & $GMX anaeig -s md.tpr -f md_fit.xtc -first 1 -last 2 -o pca_pc1_pc2.trr\n\n"
                "Write-Host \"PCA分析完成!\" -ForegroundColor Green\n"
            )
        else:
            text = ""
    
    elif "Batch" in script_type:
        gmx_batch = gmx_norm.replace("/", "\\")
        if key == "em":
            text = (
                "@echo off\n"
                "REM 能量最小化脚本模板 (Batch)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM 1. 生成拓扑 (如果已有topol.top可跳过)\n"
                "REM %GMX% pdb2gmx -f protein.pdb -o protein.gro -p topol.top -ff amber99sb-ildn -water tip3p -ignh\n\n"
                "REM 2. 构建盒子\n"
                "%GMX% editconf -f protein.gro -o protein_box.gro -c -d 1.0 -bt cubic\n\n"
                "REM 3. 溶剂化\n"
                "%GMX% solvate -cp protein_box.gro -o protein_solv.gro -p topol.top\n\n"
                "REM 4. 能量最小化\n"
                "%GMX% grompp -f em.mdp -c protein_solv.gro -p topol.top -o em.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm em -v\n"
                "if errorlevel 1 goto error\n\n"
                "echo 能量最小化完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "full_md":
            text = (
                "@echo off\n"
                "REM 完整MD流程脚本模板 (EM -> NVT -> NPT -> MD)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM EM 能量最小化\n"
                "echo ==== 运行 EM ====\n"
                "%GMX% grompp -f em.mdp -c protein_solv.gro -r protein_solv.gro -p topol.top -o em.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm em -v\n"
                "if errorlevel 1 goto error\n"
                "echo EM 完成\n\n"
                "REM NVT 恒温平衡\n"
                "echo ==== 运行 NVT ====\n"
                "%GMX% grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm nvt -v\n"
                "if errorlevel 1 goto error\n"
                "echo NVT 完成\n\n"
                "REM NPT 恒压平衡\n"
                "echo ==== 运行 NPT ====\n"
                "%GMX% grompp -f npt.mdp -c nvt.gro -r nvt.gro -p topol.top -o npt.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm npt -v\n"
                "if errorlevel 1 goto error\n"
                "echo NPT 完成\n\n"
                "REM MD 生产模拟\n"
                "echo ==== 运行 MD ====\n"
                "%GMX% grompp -f md.mdp -c npt.gro -r npt.gro -p topol.top -o md.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm md -v\n"
                "if errorlevel 1 goto error\n"
                "echo MD 完成\n\n"
                "echo 所有MD步骤完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "rmsd":
            text = (
                "@echo off\n"
                "REM RMSD分析脚本模板\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM 先做轨迹拟合 (去除平动转动)\n"
                "echo 4 | %GMX% trjconv -s md.tpr -f md.xtc -o md_fit.xtc -fit rot+trans\n\n"
                "REM 计算RMSD (骨架原子)\n"
                "echo 4 4 | %GMX% rms -s md.tpr -f md_fit.xtc -o rmsd.xvg -tu ns\n\n"
                "REM 计算RMSF\n"
                "echo 3 | %GMX% rmsf -s md.tpr -f md_fit.xtc -o rmsf.xvg -res\n\n"
                "echo RMSD/RMSF分析完成!\n"
            )
        elif key == "clffcl_em_npt":
            text = (
                "@echo off\n"
                "REM ClFFCl EM+NPT流程模板 (Batch)\n"
                "REM 流程: EM-1 → EM-2 → NPT-1 → NPT-2\n"
                "REM 使用文件: ydw-em_01.mdp (steep), ydw-em_02.mdp (cg), ydw-npt_01.mdp (1ns), ydw-npt_02.mdp (2ns)\n"
                "REM 输入: ydw-PM6-ClFFCl.pdb, p4PM6-ClFFCl-mix.top\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM ==== Step 1: 能量最小化 EM-1 (steep) ====\n"
                "echo ==== 运行 EM-1 ====\n"
                "%GMX% grompp -f ydw-em_01.mdp -c ydw-PM6-ClFFCl.pdb -p p4PM6-ClFFCl-mix.top -o ClFFCl_em1.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm ClFFCl_em1 -nt 6 -pin on -nb gpu -pme cpu\n"
                "if errorlevel 1 goto error\n"
                "echo EM-1 完成\n\n"
                "REM ==== Step 2: 能量最小化 EM-2 (cg) ====\n"
                "echo ==== 运行 EM-2 ====\n"
                "%GMX% grompp -f ydw-em_02.mdp -c ClFFCl_em1.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_em2.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm ClFFCl_em2 -nt 6 -pin on -nb gpu -pme cpu\n"
                "if errorlevel 1 goto error\n"
                "echo EM-2 完成\n\n"
                "REM ==== Step 3: NPT 平衡 1 (1ns) ====\n"
                "echo ==== 运行 NPT-1 ====\n"
                "%GMX% grompp -f ydw-npt_01.mdp -c ClFFCl_em2.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_npt1.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm ClFFCl_npt1 -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if errorlevel 1 goto error\n"
                "echo NPT-1 完成\n\n"
                "REM ==== Step 4: NPT 平衡 2 (2ns) ====\n"
                "echo ==== 运行 NPT-2 ====\n"
                "%GMX% grompp -f ydw-npt_02.mdp -c ClFFCl_npt1.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_npt2.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm ClFFCl_npt2 -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if errorlevel 1 goto error\n"
                "echo NPT-2 完成\n\n"
                "echo 所有步骤完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "clffcl_sa":
            text = (
                "@echo off\n"
                "REM ClFFCl SA溶剂蒸发流程模板 (Batch)\n"
                "REM 流程: 逐步删除CF溶剂分子，每轮运行10ps NPT\n"
                "REM 使用文件: ydw-npt-sa.mdp\n"
                "REM 输入: ClFFCl_npt2.gro, p4PM6-ClFFCl-mix.top\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "set inputGro=ClFFCl_npt2.gro\n"
                "set topFile=p4PM6-ClFFCl-mix.top\n"
                "set mdpFile=ydw-npt-sa.mdp\n"
                "set prefix=ClFFCl_sa\n"
                "set loops=500\n"
                "set deleteNum=100\n"
                "set atomsPerSolvent=5\n"
                "REM 备份原始文件\n"
                "copy /Y %inputGro% %prefix%_original.gro\n"
                "copy /Y %topFile% %prefix%_original.top\n"
                "echo 已备份原始文件\n\n"
                "set workGro=%prefix%_work.gro\n"
                "set workTop=%prefix%_work.top\n"
                "set currentGro=%prefix%_current.gro\n"
                "set currentTop=%prefix%_current.top\n"
                "copy /Y %inputGro% %workGro%\n"
                "copy /Y %topFile% %workTop%\n\n"
                "for /l %%i in (1,1,%loops%) do (\n"
                "    echo ==== SA 第 %%i/%loops% 轮 ====\n"
                "    set newGro=%prefix%_new.gro\n"
                "    set newTop=%prefix%_new.top\n"
                "    echo 删除 %deleteNum% 个CF溶剂分子...\n"
                "    python delete_solvent.py --solvent CF --delete-num %deleteNum% --atoms-per-mol %atomsPerSolvent% --loop %%i --input %workGro% --output %newGro% --topology %workTop% --topology-output %newTop%\n"
                "    if errorlevel 1 goto error\n"
                "    move /Y %newGro% %workGro%\n"
                "    move /Y %newTop% %workTop%\n"
                "    echo grompp...\n"
                "    %GMX% grompp -f %mdpFile% -c %workGro% -p %workTop% -o %prefix%_%%i.tpr -maxwarn 200\n"
                "    if errorlevel 1 goto error\n"
                "    echo mdrun (10ps)...\n"
                "    %GMX% mdrun -v -deffnm %prefix%_%%i -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "    if errorlevel 1 goto error\n"
                "    copy /Y %prefix%_%%i.gro %currentGro%\n"
                "    copy /Y %workTop% %currentTop%\n"
                "    echo 第 %%i 轮完成\n"
                ")\n\n"
                "echo SA溶剂蒸发完成!\n"
                "echo 最终结构: %currentGro%\n"
                "echo 最终拓扑: %currentTop%\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "clffcl_evapdio":
            text = (
                "@echo off\n"
                "REM ClFFCl evapDIO流程模板 (Batch)\n"
                "REM 流程: 删除DIO添加剂 → 运行1ns NPT平衡 → 退火 → MD2\n"
                "REM 使用文件: ydw-evapDIO.mdp, ydw-ta.mdp, ydw-md_02.mdp\n"
                "REM 输入: ClFFCl_md.gro, ClFFCl_sa_current.top\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "set inputGro=ClFFCl_md.gro\n"
                "set inputTop=ClFFCl_sa_current.top\n"
                "set mdpFile=ydw-evapDIO.mdp\n"
                "set prefix=ClFFCl_evapDIO\n\n"
                "REM ==== Step 1: 删除DIO添加剂 ====\n"
                "echo ==== 删除DIO添加剂 ====\n"
                "set outGro=%prefix%_DA.gro\n"
                "set outTop=%prefix%.top\n"
                "python delete_additive_all.py --additive DIO --atoms-per-mol 6 --input %inputGro% --output %outGro% --topology %inputTop% --topology-output %outTop%\n"
                "if errorlevel 1 goto error\n"
                "echo DIO删除完成\n\n"
                "REM ==== Step 2: 1ns NPT平衡 ====\n"
                "echo ==== 运行1ns NPT平衡 ====\n"
                "%GMX% grompp -f %mdpFile% -c %prefix%_DA.gro -p %prefix%.top -o %prefix%.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm %prefix% -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if errorlevel 1 goto error\n"
                "echo evapDIO NPT完成\n\n"
                "REM ==== Step 3: 退火过程 ====\n"
                "echo ==== 运行退火 ====\n"
                "%GMX% grompp -f ydw-ta.mdp -c %prefix%.gro -p %prefix%.top -o %prefix%_anneal.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm %prefix%_anneal -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if errorlevel 1 goto error\n"
                "echo 退火完成\n\n"
                "REM ==== Step 4: MD2 生产模拟 ====\n"
                "echo ==== 运行MD2 ====\n"
                "%GMX% grompp -f ydw-md_02.mdp -c %prefix%_anneal.gro -p %prefix%.top -o %prefix%_md2.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm %prefix%_md2 -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if errorlevel 1 goto error\n"
                "echo MD2完成\n\n"
                "echo evapDIO流程完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "clffcl_md1":
            text = (
                "@echo off\n"
                "REM ClFFCl MD-1生产模拟流程模板 (Batch)\n"
                "REM 流程: 基于ClFFCl_npt2.gro运行10ns生产模拟\n"
                "REM 使用文件: ydw-md_01.mdp (10ns)\n"
                "REM 输入: ClFFCl_npt2.gro, p4PM6-ClFFCl-mix.top\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM ==== Step 1: MD-1 生产模拟 (10ns) ====\n"
                "echo ==== 运行 MD-1 (10ns) ====\n"
                "%GMX% grompp -f ydw-md_01.mdp -c ClFFCl_npt2.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_md.tpr -maxwarn 200\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -v -deffnm ClFFCl_md -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
                "if errorlevel 1 goto error\n"
                "echo MD-1 (10ns)完成\n\n"
                "echo ClFFCl MD-1生产模拟完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "nvt":
            text = (
                "@echo off\n"
                "REM NVT恒温平衡脚本模板 (Batch)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM NVT 恒温平衡\n"
                "echo ==== 运行 NVT 恒温平衡 ====\n"
                "%GMX% grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm nvt -v\n"
                "if errorlevel 1 goto error\n"
                "echo NVT恒温平衡完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "npt":
            text = (
                "@echo off\n"
                "REM NPT恒压平衡脚本模板 (Batch)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM NPT 恒压平衡\n"
                "echo ==== 运行 NPT 恒压平衡 ====\n"
                "%GMX% grompp -f npt.mdp -c nvt.gro -r nvt.gro -p topol.top -o npt.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm npt -v\n"
                "if errorlevel 1 goto error\n"
                "echo NPT恒压平衡完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "md":
            text = (
                "@echo off\n"
                "REM MD生产模拟脚本模板 (Batch)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM MD 生产模拟\n"
                "echo ==== 运行 MD 生产模拟 ====\n"
                "%GMX% grompp -f md.mdp -c npt.gro -r npt.gro -p topol.top -o md.tpr -maxwarn 2\n"
                "if errorlevel 1 goto error\n"
                "%GMX% mdrun -deffnm md -v\n"
                "if errorlevel 1 goto error\n"
                "echo MD生产模拟完成!\n"
                "goto end\n"
                ":error\n"
                "echo 执行失败!\n"
                ":end\n"
            )
        elif key == "rdf":
            text = (
                "@echo off\n"
                "REM RDF径向分布函数分析脚本模板 (Batch)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM 计算径向分布函数 (蛋白-溶剂)\n"
                "echo 1 11 | %GMX% rdf -s md.tpr -f md.xtc -o rdf.xvg -ref 'Protein' -sel 'Water'\n\n"
                "REM 计算配位数\n"
                "echo 1 11 | %GMX% rdf -s md.tpr -f md.xtc -o rdf_coord.xvg -ref 'Protein' -sel 'Water' -cn\n\n"
                "echo RDF分析完成!\n"
            )
        elif key == "hbond":
            text = (
                "@echo off\n"
                "REM 氢键分析脚本模板 (Batch)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM 计算氢键 (蛋白-蛋白)\n"
                "echo 1 1 | %GMX% hbond -s md.tpr -f md.xtc -num hbond.xvg\n\n"
                "REM 计算氢键 (蛋白-溶剂)\n"
                "echo 1 11 | %GMX% hbond -s md.tpr -f md.xtc -num hbond_solv.xvg\n\n"
                "REM 氢键寿命分析\n"
                "echo 1 1 | %GMX% hbond -s md.tpr -f md.xtc -ac hbond_analysis.xvg\n\n"
                "echo 氢键分析完成!\n"
            )
        elif key == "sasa":
            text = (
                "@echo off\n"
                "REM SASA溶剂可及面积分析脚本模板 (Batch)\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM 计算整体SASA\n"
                "echo 1 | %GMX% sasa -s md.tpr -f md.xtc -o sasa.xvg -surface 1 -output 1\n\n"
                "REM 按残基计算SASA\n"
                "echo 3 | %GMX% sasa -s md.tpr -f md.xtc -o sasa_res.xvg -surface 1 -output 2\n\n"
                "REM 计算极性/非极性SASA\n"
                "echo 1 | %GMX% sasa -s md.tpr -f md.xtc -o sasa_pol.xvg -surface 2 -output 1\n\n"
                "echo SASA分析完成!\n"
            )
        elif key == "pca":
            text = (
                "@echo off\n"
                "REM PCA主成分分析脚本模板 (Batch)\n"
                "REM 注意：需要先做轨迹拟合\n"
                "set GMX=" + gmx_batch + "\n"
                "cd /d %~dp0\n\n"
                "REM 步骤1: 轨迹拟合 (去除平动转动)\n"
                "echo ==== 轨迹拟合 ====\n"
                "echo 4 | %GMX% trjconv -s md.tpr -f md.xtc -o md_fit.xtc -fit rot+trans\n\n"
                "REM 步骤2: 计算协方差矩阵\n"
                "echo ==== 计算协方差矩阵 ====\n"
                "echo 4 | %GMX% covar -s md.tpr -f md_fit.xtc -o eigenvectors.trr -xpm covar.xpm\n\n"
                "REM 步骤3: 对角化协方差矩阵\n"
                "echo ==== 对角化协方差矩阵 ====\n"
                "%GMX% anaeig -s md.tpr -f eigenvectors.trr -o eigenvalues.xvg -v eigenvectors.trr -n 10\n\n"
                "REM 步骤4: 投影到主成分\n"
                "echo ==== 投影到主成分 ====\n"
                "echo 4 | %GMX% anaeig -s md.tpr -f md_fit.xtc -proj pcaprojection.xvg\n\n"
                "echo PCA分析完成!\n"
            )
        else:
            text = ""
    
    elif "Shell" in script_type:
        if key == "em":
            text = "# 能量最小化脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# 1. 生成拓扑 (如果已有topol.top可跳过)\n"
            text += "# " + gmx_norm + " pdb2gmx -f protein.pdb -o protein.gro -p topol.top -ff amber99sb-ildn -water tip3p -ignh\n\n"
            text += "# 2. 构建盒子\n"
            text += gmx_norm + " editconf -f protein.gro -o protein_box.gro -c -d 1.0 -bt cubic\n\n"
            text += "# 3. 溶剂化\n"
            text += gmx_norm + " solvate -cp protein_box.gro -o protein_solv.gro -p topol.top\n\n"
            text += "# 4. 能量最小化\n"
            text += gmx_norm + " grompp -f em.mdp -c protein_solv.gro -p topol.top -o em.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm em -v\n"
        elif key == "full_md":
            text = "# 完整MD流程脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# EM 能量最小化\n"
            text += gmx_norm + " grompp -f em.mdp -c protein_solv.gro -r protein_solv.gro -p topol.top -o em.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm em -v\n\n"
            text += "# NVT 恒温平衡\n"
            text += gmx_norm + " grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm nvt -v\n\n"
            text += "# NPT 恒压平衡\n"
            text += gmx_norm + " grompp -f npt.mdp -c nvt.gro -r nvt.gro -p topol.top -o npt.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm npt -v\n\n"
            text += "# MD 生产模拟\n"
            text += gmx_norm + " grompp -f md.mdp -c npt.gro -r npt.gro -p topol.top -o md.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm md -v\n"
        elif key == "clffcl_em_npt":
            text = "# ClFFCl EM+NPT流程模板 (Shell命令)\n"
            text += "# 流程: EM-1 → EM-2 → NPT-1 → NPT-2\n"
            text += "# 使用文件: ydw-em_01.mdp (steep), ydw-em_02.mdp (cg), ydw-npt_01.mdp (1ns), ydw-npt_02.mdp (2ns)\n"
            text += "# 输入: ydw-PM6-ClFFCl.pdb, p4PM6-ClFFCl-mix.top\n\n"
            text += "# ==== Step 1: 能量最小化 EM-1 (steep) ====\n"
            text += gmx_norm + " grompp -f ydw-em_01.mdp -c ydw-PM6-ClFFCl.pdb -p p4PM6-ClFFCl-mix.top -o ClFFCl_em1.tpr -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm ClFFCl_em1 -nt 6 -pin on -nb gpu -pme cpu\n\n"

            text += "# ==== Step 2: 能量最小化 EM-2 (cg) ====\n"
            text += gmx_norm + " grompp -f ydw-em_02.mdp -c ClFFCl_em1.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_em2.tpr -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm ClFFCl_em2 -nt 6 -pin on -nb gpu -pme cpu\n\n"

            text += "# ==== Step 3: NPT 平衡 1 (1ns) ====\n"
            text += gmx_norm + " grompp -f ydw-npt_01.mdp -c ClFFCl_em2.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_npt1.tpr -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm ClFFCl_npt1 -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n\n"
            text += "# ==== Step 4: NPT 平衡 2 (2ns) ====\n"
            text += gmx_norm + " grompp -f ydw-npt_02.mdp -c ClFFCl_npt1.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_npt2.tpr -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm ClFFCl_npt2 -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n\n"
            text += "echo '所有步骤完成!'\n"
        elif key == "clffcl_sa":
            text = "# ClFFCl SA溶剂蒸发流程模板 (Shell命令)\n"
            text += "# 流程: 逐步删除CF溶剂分子，每轮运行10ps NPT\n"
            text += "# 使用文件: ydw-npt-sa.mdp\n"
            text += "# 输入: ClFFCl_npt2.gro, p4PM6-ClFFCl-mix.top\n\n"
            text += "inputGro=\"ClFFCl_npt2.gro\"\n"
            text += "topFile=\"p4PM6-ClFFCl-mix.top\"\n"
            text += "mdpFile=\"ydw-npt-sa.mdp\"\n"
            text += "prefix=\"ClFFCl_sa\"\n"
            text += "loops=500\n"
            text += "deleteNum=100\n"
            text += "atomsPerSolvent=5\n"
            text += "# 备份原始文件\n"
            text += "cp \"$inputGro\" \"${prefix}_original.gro\"\n"
            text += "cp \"$topFile\" \"${prefix}_original.top\"\n"
            text += "echo \"已备份原始文件\"\n\n"
            text += "workGro=\"${prefix}_work.gro\"\n"
            text += "workTop=\"${prefix}_work.top\"\n"
            text += "currentGro=\"${prefix}_current.gro\"\n"
            text += "currentTop=\"${prefix}_current.top\"\n"
            text += "cp \"$inputGro\" \"$workGro\"\n"
            text += "cp \"$topFile\" \"$workTop\"\n\n"
            text += "for ((i=1; i<=loops; i++)); do\n"
            text += "  echo \"==== SA 第 $i/$loops 轮 ====\"\n"
            text += "  newGro=\"${prefix}_new.gro\"\n"
            text += "  newTop=\"${prefix}_new.top\"\n"
            text += "  echo \"删除 $deleteNum 个CF溶剂分子...\"\n"
            text += "  python delete_solvent.py --solvent CF --delete-num \"$deleteNum\" --atoms-per-mol \"$atomsPerSolvent\" --loop \"$i\" --input \"$workGro\" --output \"$newGro\" --topology \"$workTop\" --topology-output \"$newTop\"\n"
            text += "  if [ $? -ne 0 ]; then echo \"删除溶剂失败\"; exit 1; fi\n"
            text += "  mv \"$newGro\" \"$workGro\"\n"
            text += "  mv \"$newTop\" \"$workTop\"\n"
            text += "  echo \"grompp...\"\n"
            text += "  " + gmx_norm + " grompp -f \"$mdpFile\" -c \"$workGro\" -p \"$workTop\" -o \"${prefix}_$i.tpr\" -maxwarn 200\n"
            text += "  if [ $? -ne 0 ]; then echo \"grompp失败\"; exit 1; fi\n"
            text += "  echo \"mdrun (10ps)...\"\n"
            text += "  " + gmx_norm + " mdrun -v -deffnm \"${prefix}_$i\" -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
            text += "  if [ $? -ne 0 ]; then echo \"mdrun失败\"; exit 1; fi\n"
            text += "  cp \"${prefix}_$i.gro\" \"$currentGro\"\n"
            text += "  cp \"$workTop\" \"$currentTop\"\n"
            text += "  echo \"第 $i 轮完成\"\n"
            text += "done\n\n"
            text += "echo 'SA溶剂蒸发完成!'\n"
            text += "echo \"最终结构: $currentGro\"\n"
            text += "echo \"最终拓扑: $currentTop\"\n"
        elif key == "clffcl_evapdio":
            text = "# ClFFCl evapDIO流程模板 (Shell命令)\n"
            text += "# 流程: 删除DIO添加剂 → 运行1ns NPT平衡 → 退火 → MD2\n"
            text += "# 使用文件: ydw-evapDIO.mdp, ydw-ta.mdp, ydw-md_02.mdp\n"
            text += "# 输入: ClFFCl_md.gro, ClFFCl_sa_current.top\n\n"
            text += "inputGro=\"ClFFCl_md.gro\"\n"
            text += "inputTop=\"ClFFCl_sa_current.top\"\n"
            text += "mdpFile=\"ydw-evapDIO.mdp\"\n"
            text += "prefix=\"ClFFCl_evapDIO\"\n\n"
            text += "# ==== Step 1: 删除DIO添加剂 ====\n"
            text += "echo \"==== 删除DIO添加剂 ====\"\n"
            text += "outGro=\"${prefix}_DA.gro\"\n"
            text += "outTop=\"${prefix}.top\"\n"
            text += "python delete_additive_all.py --additive DIO --atoms-per-mol 6 --input \"$inputGro\" --output \"$outGro\" --topology \"$inputTop\" --topology-output \"$outTop\"\n"
            text += "echo 'DIO删除完成'\n\n"
            text += "# ==== Step 2: 1ns NPT平衡 ====\n"
            text += "echo \"==== 运行1ns NPT平衡 ====\"\n"
            text += gmx_norm + " grompp -f \"$mdpFile\" -c \"${prefix}_DA.gro\" -p \"${prefix}.top\" -o \"${prefix}.tpr\" -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm \"$prefix\" -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
            text += "echo 'evapDIO NPT完成'\n\n"
            text += "# ==== Step 3: 退火过程 ====\n"
            text += "echo \"==== 运行退火 ====\"\n"
            text += gmx_norm + " grompp -f ydw-ta.mdp -c \"${prefix}.gro\" -p \"${prefix}.top\" -o \"${prefix}_anneal.tpr\" -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm \"${prefix}_anneal\" -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
            text += "echo '退火完成'\n\n"
            text += "# ==== Step 4: MD2 生产模拟 ====\n"
            text += "echo \"==== 运行MD2 ====\"\n"
            text += gmx_norm + " grompp -f ydw-md_02.mdp -c \"${prefix}_anneal.gro\" -p \"${prefix}.top\" -o \"${prefix}_md2.tpr\" -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm \"${prefix}_md2\" -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
            text += "echo 'MD2完成'\n\n"
            text += "echo 'evapDIO+退火+MD2流程全部完成!'\n"
        elif key == "rmsd":
            text = "# RMSD分析脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# 先做轨迹拟合 (去除平动转动)\n"
            text += "echo 4 | " + gmx_norm + " trjconv -s md.tpr -f md.xtc -o md_fit.xtc -fit rot+trans\n\n"
            text += "# 计算RMSD (骨架原子)\n"
            text += "echo 4 4 | " + gmx_norm + " rms -s md.tpr -f md_fit.xtc -o rmsd.xvg -tu ns\n\n"
            text += "# 计算RMSF\n"
            text += "echo 3 | " + gmx_norm + " rmsf -s md.tpr -f md_fit.xtc -o rmsf.xvg -res\n"
        elif key == "clffcl_md1":
            text = "# ClFFCl MD-1生产模拟流程模板 (Shell命令)\n"
            text += "# 流程: 基于ClFFCl_npt2.gro运行10ns生产模拟\n"
            text += "# 使用文件: ydw-md_01.mdp (10ns)\n"
            text += "# 输入: ClFFCl_npt2.gro, p4PM6-ClFFCl-mix.top\n\n"
            text += "# ==== Step 1: MD-1 生产模拟 (10ns) ====\n"
            text += "echo \"==== 运行 MD-1 (10ns) ====\"\n"
            text += gmx_norm + " grompp -f ydw-md_01.mdp -c ClFFCl_npt2.gro -p p4PM6-ClFFCl-mix.top -o ClFFCl_md.tpr -maxwarn 200\n"
            text += gmx_norm + " mdrun -v -deffnm ClFFCl_md -nt 6 -pin on -gpu_id 0 -nb gpu -pme gpu -bonded gpu -update gpu\n"
            text += "echo 'MD-1 (10ns)完成'\n\n"
            text += "echo 'ClFFCl MD-1生产模拟完成!'\n"
        elif key == "nvt":
            text = "# NVT恒温平衡脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# NVT 恒温平衡\n"
            text += "echo \"==== 运行 NVT 恒温平衡 ====\"\n"
            text += gmx_norm + " grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm nvt -v\n"
            text += "echo 'NVT恒温平衡完成!'\n"
        elif key == "npt":
            text = "# NPT恒压平衡脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# NPT 恒压平衡\n"
            text += "echo \"==== 运行 NPT 恒压平衡 ====\"\n"
            text += gmx_norm + " grompp -f npt.mdp -c nvt.gro -r nvt.gro -p topol.top -o npt.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm npt -v\n"
            text += "echo 'NPT恒压平衡完成!'\n"
        elif key == "md":
            text = "# MD生产模拟脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# MD 生产模拟\n"
            text += "echo \"==== 运行 MD 生产模拟 ====\"\n"
            text += gmx_norm + " grompp -f md.mdp -c npt.gro -r npt.gro -p topol.top -o md.tpr -maxwarn 2\n"
            text += gmx_norm + " mdrun -deffnm md -v\n"
            text += "echo 'MD生产模拟完成!'\n"
        elif key == "rdf":
            text = "# RDF径向分布函数分析脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# 计算径向分布函数 (蛋白-溶剂)\n"
            text += "echo 1 11 | " + gmx_norm + " rdf -s md.tpr -f md.xtc -o rdf.xvg -ref 'Protein' -sel 'Water'\n\n"
            text += "# 计算配位数\n"
            text += "echo 1 11 | " + gmx_norm + " rdf -s md.tpr -f md.xtc -o rdf_coord.xvg -ref 'Protein' -sel 'Water' -cn\n\n"
            text += "echo 'RDF分析完成!'\n"
        elif key == "hbond":
            text = "# 氢键分析脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# 计算氢键 (蛋白-蛋白)\n"
            text += "echo 1 1 | " + gmx_norm + " hbond -s md.tpr -f md.xtc -num hbond.xvg\n\n"
            text += "# 计算氢键 (蛋白-溶剂)\n"
            text += "echo 1 11 | " + gmx_norm + " hbond -s md.tpr -f md.xtc -num hbond_solv.xvg\n\n"
            text += "# 氢键寿命分析\n"
            text += "echo 1 1 | " + gmx_norm + " hbond -s md.tpr -f md.xtc -ac hbond_analysis.xvg\n\n"
            text += "echo '氢键分析完成!'\n"
        elif key == "sasa":
            text = "# SASA溶剂可及面积分析脚本模板 (Shell命令)\n"
            text += "# 一行一条命令，依次执行\n\n"
            text += "# 计算整体SASA\n"
            text += "echo 1 | " + gmx_norm + " sasa -s md.tpr -f md.xtc -o sasa.xvg -surface 1 -output 1\n\n"
            text += "# 按残基计算SASA\n"
            text += "echo 3 | " + gmx_norm + " sasa -s md.tpr -f md.xtc -o sasa_res.xvg -surface 1 -output 2\n\n"
            text += "# 计算极性/非极性SASA\n"
            text += "echo 1 | " + gmx_norm + " sasa -s md.tpr -f md.xtc -o sasa_pol.xvg -surface 2 -output 1\n\n"
            text += "echo 'SASA分析完成!'\n"
        elif key == "pca":
            text = "# PCA主成分分析脚本模板 (Shell命令)\n"
            text += "# 注意：需要先做轨迹拟合\n\n"
            text += "# 步骤1: 轨迹拟合 (去除平动转动)\n"
            text += "echo \"==== 轨迹拟合 ====\"\n"
            text += "echo 4 | " + gmx_norm + " trjconv -s md.tpr -f md.xtc -o md_fit.xtc -fit rot+trans\n\n"
            text += "# 步骤2: 计算协方差矩阵\n"
            text += "echo \"==== 计算协方差矩阵 ====\"\n"
            text += "echo 4 | " + gmx_norm + " covar -s md.tpr -f md_fit.xtc -o eigenvectors.trr -xpm covar.xpm\n\n"
            text += "# 步骤3: 对角化协方差矩阵\n"
            text += "echo \"==== 对角化协方差矩阵 ====\"\n"
            text += gmx_norm + " anaeig -s md.tpr -f eigenvectors.trr -o eigenvalues.xvg -v eigenvectors.trr -n 10\n\n"
            text += "# 步骤4: 投影到主成分\n"
            text += "echo \"==== 投影到主成分 ====\"\n"
            text += "echo 4 | " + gmx_norm + " anaeig -s md.tpr -f md_fit.xtc -proj pcaprojection.xvg\n\n"
            text += "# 步骤5: 生成PC1和PC2的结构\n"
            text += "echo \"==== 生成主成分结构 ====\"\n"
            text += "echo 4 | " + gmx_norm + " anaeig -s md.tpr -f md_fit.xtc -first 1 -last 2 -o pca_pc1_pc2.trr\n\n"
            text += "echo 'PCA分析完成!'\n"
        else:
            text = ""
    
    else:
        text = ""
    

    return text
